### ISSUE TITLE
Crashes my game when I go to customize

### ISSUE THREAD

**Issue by TheDarkPanther** [racoonman2/ReTerraForged#100]
is there a mod that helps load it I can't seem to get it to load

**Comment by racoonman2** [comment]
i dont provide support for the current builds, please do not report issues with them

**Comment by TheDarkPanther** [comment]
Then why have a version for it on 1.20.1 then? If you aren't gonna optimize it?

**Comment by equalizer32** [comment]
> Then why have a version for it on 1.20.1 then? If you aren't gonna optimize it?

The repository is outdated as the mod is currently being developed privatelly due to people like you trying to build it, failing and then complain on the Discord/GitHub repo. If you want to use this mod then you have to wait for 0.0.7 to release. Do not ask about any ETA or updates, it will release once it's ready.

**Comment by TheDarkPanther** [comment]
> > Then why have a version for it on 1.20.1 then? If you aren't gonna optimize it?
> 
> The repository is outdated as the mod is currently being developed privatelly due to people like you trying to build it, failing and then complain on the Discord/GitHub repo. If you want to use this mod then you have to wait for 0.0.7 to release. Do not ask about any ETA or updates, it will release once it's ready.

"people like you"? First of all I don't even know what this mod is, second of all I only seen videos of people using it 3rd of all idk I am new to this GitHub, and I was just wondering why it was crashing I found a full version on 9Minecraft that doesn't crash my game I honestly don't care what happened to your server and what they did all I know is, I saw mod and I wanted to see what it was, you can block me if you want it doesn't matter either way. geez
