### ISSUE TITLE
how do i download the mod

### ISSUE THREAD

**Issue by yeahyeahyeahyeahyeahyeahyeah** [racoonman2/ReTerraForged#106]
theres zero damn tutorials anywhere on how to download the mod, and because its not on curseforge nor on modrinth i got no idea how to download the mod on github theres just a trillion different files and ionno what to download on here bruh

**Comment by equalizer32** [comment]
There are no tutorials because the mod is not meant to be downloaded right now. It's currently in a very early pre-alpha state and thus has a lot of issues. Please wait for the official release.
