### ISSUE TITLE
Disable Water/Lava Springs

### ISSUE THREAD

**Issue by Quizer9O8** [racoonman2/reterraforged#12]
Water and lava springs are very common in ReTerraForged causing a lot of lag and FPS drops due to the destruction of vegetation and constant block updates due to the cascading of these flowing water/lava blocks. 
![2023-07-24_12 02 29](https://github.com/racoonman2/reterraforged/assets/19509275/6fe31865-9f15-424d-9a3b-f0142b268e89)
Back in TerraForged 1.16.5 there was an option to disable them entirely to prevent stuff like this from happening.

**Comment by racoonman2** [comment]
fixed in the upcoming release
