### ISSUE TITLE
Caves carve too deep

### ISSUE THREAD

**Issue by GamingCrew69** [racoonman2/reterraforged#13]
Vanilla: 
![2023-07-25_18 12 30](https://github.com/racoonman2/reterraforged/assets/85794256/227fc4e3-1857-431b-9fc8-cd3a759c2889)
ReTerraForged: 
![2023-07-25_18 10 56](https://github.com/racoonman2/reterraforged/assets/85794256/acd9835b-c61e-4ecc-a6c5-460c7fbbdd68)

**Comment by racoonman2** [comment]
fixed in the upcoming release
