### ISSUE TITLE
Ore veins can generate in the ocean

### ISSUE THREAD

**Issue by GamingCrew69** [racoonman2/reterraforged#16]
![2023-07-26_18 50 14](https://github.com/racoonman2/reterraforged/assets/85794256/129f4330-f9da-4eb4-8058-2d1db47fcd9e)
![2023-07-26_18 50 18](https://github.com/racoonman2/reterraforged/assets/85794256/aa6d6f4c-b46f-485a-adb1-7fe5bbab5258)

**Comment by racoonman2** [comment]
fixed in the upcoming release
