### ISSUE TITLE
Continent noise the Climate Biome Source uses is different from the continent noise the terrain generator uses

### ISSUE THREAD

**Issue by GamingCrew69** [racoonman2/reterraforged#23]
![2023-08-21_08 56 39](https://github.com/racoonman2/reterraforged/assets/85794256/7b74f946-df5d-4d4f-9ca7-ec0cbb74874c)
![2023-08-21_08 44 50](https://github.com/racoonman2/reterraforged/assets/85794256/82beac06-8eaf-4f0e-947c-f3b234e08d00)
![2023-08-21_08 45 08](https://github.com/racoonman2/reterraforged/assets/85794256/88728875-6ce7-4902-9463-2ff46572d5ff)
![2023-08-21_08 42 35](https://github.com/racoonman2/reterraforged/assets/85794256/f4505188-95e7-423f-89bc-77da41d73feb)

**Comment by racoonman2** [comment]
fixed
