### ISSUE TITLE
Hates BYG.

### ISSUE THREAD

**Issue by MagmaBro123** [racoonman2/ReTerraForged#32]
Title.

See https://github.com/AOCAWOL/BYG/issues/1253.

**Comment by Steveplays28** [comment]
BYG biomes generate fine on 1.20.1, not sure about the caves though

**Comment by MagmaSlime123** [comment]
> BYG biomes generate fine on 1.20.1, not sure about the caves though

Thought you fixed caves?

**Comment by Steveplays28** [comment]
Did racoonman fix them? I'm not the dev. Just passing by, this is what I've found in my testing.

**Comment by MagmaSlime123** [comment]
> Did racoonman fix them? I'm not the dev. Just passing by, this is what I've found in my testing.

Ah, whoops.
