### ISSUE TITLE
some question about transaltions

### ISSUE THREAD

**Issue by MeteorShower2004** [racoonman2/ReTerraForged#36]
Hello :D, I'm a student from China. I know my English is not very well, but I would like to contibute Chinese translation to this amazing mod.
So may I have the honor to make this contribution? And how could I  do it?
(I didn't find language mapping in resources fold.)

**Comment by racoonman2** [comment]
you have to run the runData task to generate the language file, after that it should appear in src/generated/resources/assets/reterraforged/lang

**Comment by MeteorShower2004** [comment]
Excuse me, how do I commit my file? Shall I fork the repo? Or just send the file here?

**Comment by MeteorShower2004** [comment]
I will extend class `LanguageProvider` in `RTFLanguageProvider`.

**Comment by MeteorShower2004** [comment]
Hello, I have finished the translation. So I'm wondering what should I do to commit my changes. Thank you.:D
