### ISSUE TITLE
Lava Puddles are too common

### ISSUE THREAD

**Issue by GamingCrew69** [racoonman2/reterraforged#4]
ReTerraForged: (custom biome config)
![export_3](https://github.com/racoonman2/reterraforged/assets/85794256/95507e12-fde8-4f3d-bc88-36ae4ec851f2)

Vanilla: (Single Biome - Plains)
![export_4](https://github.com/racoonman2/reterraforged/assets/85794256/416a01db-928a-4bf8-9cb1-c3380c99bb84)
 
Both worlds were generated on the same instance and both images have been exported using the same version of Xaero's World Map. The images show an area of 3000x3000 blocks and are both on a 1:1 scale

PS: Would you be kind enough to send me / share the biome config you used in these screenshots? https://discord.com/channels/687310840915165240/687310841472876577/1127357626943033394

**Comment by racoonman2** [comment]
fixed in the upcoming release
