### ISSUE TITLE
game crash when generating chunk 

### ISSUE THREAD

**Issue by dhgameryt** [racoonman2/ReTerraForged#56]
game crash when try generate new chunks, game instantly go black and dont create crash report

lastest log:
https://gist.github.com/dhgameryt/753e71f7615675cdfac92004c79f60a8

**Comment by AC5174765920** [comment]
If you are trying to generate new version chunks in an old version world, then it will crash. You can find migration methods in discord server

**Comment by racoonman2** [comment]
this looks more like its related to ice and fire, does it still happen without reterraforged?

**Comment by racoonman2** [comment]
try using the versions posted in the terraforged discord and see if it still crashes
