### ISSUE TITLE
Lava does not flood caves bellow y=-55

### ISSUE THREAD

**Issue by GamingCrew69** [racoonman2/reterraforged#6]
ReTerraForged (alpha 2 - 1.19.4)
![2023-07-20_20 45 34](https://github.com/racoonman2/reterraforged/assets/85794256/be12d251-9e3a-4079-8222-db20a4f0cc9e)

Vanilla 1.19.4
![2023-07-20_20 52 45](https://github.com/racoonman2/reterraforged/assets/85794256/3702bc63-ce32-4ac5-9c1e-89a277fd06aa)

**Comment by racoonman2** [comment]
![image](https://github.com/racoonman2/reterraforged/assets/81602236/171aa33f-7d29-4038-b6eb-e3227bd64aa8)

should be fixed now
