### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by dexsystem** [racoonman2/ReTerraForged#61]
* What went wrong:
A problem occurred configuring root project 'ReTerraForged'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.mojang:datafixerupper:6.0.8.
     Required by:
         project : > dev.architectury.loom:dev.architectury.loom.gradle.plugin:1.4-SNAPSHOT:20240124.181623-1 > dev.architectury:architectury-loom:1.4-SNAPSHOT:20240124.181623-1
      > No matching variant of com.mojang:datafixerupper:6.0.8 was found. The consumer was configured to find a library for use during runtime, compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.3' but:
          - Variant 'apiElements' capability com.mojang:datafixerupper:6.0.8 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 17 and the consumer needed a component for use during runtime, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.3')
          - Variant 'runtimeElements' capability com.mojang:datafixerupper:6.0.8 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 17 and the consumer needed a component, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.3')

how to fix that?

**Comment by equalizer32** [comment]
![hi-google](https://github.com/racoonman2/ReTerraForged/assets/85794256/15b3ae08-396c-4e97-a8a6-a813f4c859e5)
