### ISSUE TITLE
[Tutorial request] For less experienced modders

### ISSUE THREAD

**Issue by Bernini420** [racoonman2/ReTerraForged#62]
Hello I love the RTF project and have been playing using the 1.16.5 version that is up on Curse Forge, but with the newer versions of Minecraft coming out I really wish to be able to use the newer features and content of  1.20.1.

I was wondering If anyone had made the current 0.0.6 version of RTF work in 1.20.1 fabric/forge and could help out those of us who are inexperienced in the field of modding

I attempted to convert the zip for 1.20.1 to a .jar file but it didn't seem to have any effect and after reading through the launch receipt it seemed to be ignored by the launcher ( I used fabric since I mainly play on it).

I'm pretty late into finding this mod rework and didn't know a discord existed but after reading through other Issues pages I saw that It is no longer inviting new members.

I am not requesting the mod developer to bend over backwards to make this mod official but I would love if someone from the community could help us out with a tutorial.

If one already exists I am sorry in advance and would appreciate it if it could be linked in the comments.

**Comment by equalizer32** [comment]
![hi-google](https://github.com/racoonman2/ReTerraForged/assets/85794256/36a38f27-71ab-40d9-82ec-0defe4435abe)

You can easily find how to compile mods on google

**Comment by FluffyPuppyKasey** [comment]
1. Clone the github repo
2. Open a terminal, change directory to the cloned repo, then run `gradlew.bat build`
3. Profit
