### ISSUE TITLE
1.20.4/1.20.6/1.21 support

### ISSUE THREAD

**Issue by danosito** [racoonman2/ReTerraForged#63]
I know, that this might sound stupid, but i didn't found any mention of 1.20.4 rtf. My friends and i are playing on this version, so is there any opportunity to build it to 1.20.4? If so, how can I do it? I know how to build mods, but my knowledge is not large, so I'm asking this (maybe) stupid question.

**Comment by equalizer32** [comment]
1.20.4 support will come in 0.0.7

**Comment by piksanio** [comment]
any news on when that's gonna be out?

**Comment by equalizer32** [comment]
> any news on when that's gonna be out?

It's gonna be out when it's gonna be out.

**Comment by Xytriza** [comment]
skull

**Comment by VC9334** [comment]
Wha du hel

**Comment by abricoshka** [comment]
You can just generate world with reterraforged in 1.20.2. Then open it in 1.20.4. 

Here is the working rtf 0.0.6 for fabric 1.20.2.
https://cdn.discordapp.com/attachments/1220424464479682570/1220580631772270652/reterraforged-0.0.6-fabric-1.20.2.jar?ex=66c958cb&is=66c8074b&hm=839db854cfe1071943df534f634b5f53f1ba91caab6f37a3689a0a4d821134da&

**Comment by LeonLeKan** [comment]
It seems that the development is currently paused.
Maybe the creator needs to take a break...

**Comment by yntha** [comment]
> You can just generate world with reterraforged in 1.20.2. Then open it in 1.20.4.
> 
> Here is the working rtf 0.0.6 for fabric 1.20.6 https://cdn.discordapp.com/attachments/1220424464479682570/1220580631772270652/reterraforged-0.0.6-fabric-1.20.2.jar?ex=665fe0cb&is=665e8f4b&hm=e264cf97f333e97e4d9ad3f9885f89d08122258ccc66e49f45c968029fb9697c&

dead link

**Comment by abricoshka** [comment]
> dead link

I updated the link

**Comment by WhoMustNotBeNamed** [comment]
> > dead link
> 
> I updated the link

Can you update the link again?

**Comment by VC9334** [comment]
👍🏿

ในวันที่ ศ. 8 พ.ย. 2024 20:22 น. racoonman ***@***.***>
เขียนว่า:

**Comment by rainbowboii** [comment]
Waiting for 1.21.4 coz its only better stable ver now
i like what you did guys, hope it will be soon

**Comment by equalizer32** [comment]
> Waiting for 1.21.4 coz its only better stable ver now i like what you did guys, hope it will be soon
RTF is currently being developed for 1.21.5 with a 1.21.4 port at release being very likely. As for the release date: it will release once it's ready.
