### ISSUE TITLE
1.18 Support?

### ISSUE THREAD

**Issue by PPlayer31** [racoonman2/ReTerraForged#64]
I understand quite well the difficulties of making biomes and modifying terrain for forge 1.18.
Thank you for revitalizing TerraForged, I must praise you or your efforts for how far you have come.

My request is if it would be possible to port ReTerraForged to 1.18.2, which (as far as I can recall) is the latest major version.
Obviously there is no pressure, I cannot ask you something like this before you have even finished the 1.20+ versions. I am only inquiring if you intend to consider 1.18.2 in the future.

I advise you to search which versions are most played and if 1.18 is not on the top then ignore my request entirely.

(How about 1.19.2 though?)

Good luck on achieving your goal of completing the mod.

**Comment by PPlayer31** [comment]
btw i absolutely understand if you say no. this is a question not a request.

**Comment by equalizer32** [comment]
It was originally planned but when RTF transitioned to 1.20.x it was cancelled. 1.19.4 has a pretty decent chance of happening but below that is less likely. There is still a chance tho. From my experience with modding a 1.19.2 to 1.18.2 port is easier than a 1.19.4 to 1.19.2 port, so if a 1.19.2 port happens there is a good chance of 1.18.2 happening too.

**Comment by PPlayer31** [comment]
Ah thanks for informing me. Good luck.
