### ISSUE TITLE
Bedrock edition

### ISSUE THREAD

**Issue by MisamotoGames** [racoonman2/ReTerraForged#65]
does this mod have any Bedrock edition version?

**Comment by equalizer32** [comment]
**NO.**

**Comment by Syclusion** [comment]
Considering the inadequacies of bedrock edition in modding aspects. Thats kinda like asking "can I put a lamborghini motor in my infant's gocart toy?"

TLDR: buy java

**Comment by PPlayer31** [comment]
No way. This could never be made for Bedrock.

**Comment by MisamotoGames** [comment]
bro ok ok I already have java wtf I'll just generate it in java (with also loading over 160x160 chunks) then convert it into bedrock chill
I just asked a simple question lol

**Comment by MisamotoGames** [comment]
aka for other who will ask about BE version

(just use java to generate it then convert the world to bedrock edition

the chunk blending system should do the trick)
