### ISSUE TITLE
How to use reterraforged 0.0.4

### ISSUE THREAD

**Issue by Alessandro5558** [racoonman2/ReTerraForged#66]
Hi I wanted to ask how to use reterraforged 0.0.4 I know it's not the latest but it's the latest for 1.19.4 I wanted to know how to create a world with the default preset

**Comment by equalizer32** [comment]
You select the default world type and click the customize button next to it, then you select the preset you want.

**Comment by Alessandro5558** [comment]
there is no preset ![image](https://github.com/racoonman2/ReTerraForged/assets/98539154/a17f6d25-f034-4530-9fcb-23c67c89155f)
