### ISSUE TITLE
1.19.2 support

### ISSUE THREAD

**Issue by CFog1** [racoonman2/ReTerraForged#69]
Will Reterraforged ever have a 1.19.2 version of it? I hope it will.

**Comment by equalizer32** [comment]
I am not a dev so I can't say for sure, but there is a good chance of 1.19.4 happening and if there isn't an official version for 1.19.2 then people will most likely make an unofficial port

**Comment by vgrynch** [comment]
+, need 1.19.2

**Comment by PPlayer31** [comment]
I also hope it will be ported to 1.19.2. By the way will it ever be released on curseforge?

**Comment by CFog1** [comment]
> I am not a dev so I can't say for sure, but there is a good chance of 1.19.4 happening and if there isn't an official version for 1.19.2 then people will most likely make an unofficial port

yeah someone might do an unofficial port or I might do it myself.

**Comment by JimBob-bb** [comment]
Keep me posted, I would love if there was a version for 1.19.2.

**Comment by JavaCoder5542884** [comment]
Yes please

**Comment by adrianiurian** [comment]
I would also like a 1.19.2 version of this mod. If there is anything I can do to help maybe develop it faster let me know.

**Comment by QianFuv** [comment]
1.19.2 plz

**Comment by phucn3101** [comment]
really looking forward to a 1.19.2 version.

**Comment by racoonman2** [comment]
unfortunately too much of the code is dependent on 1.20+ for this to really be practical anymore
