### ISSUE TITLE
error gradelw.bat

### ISSUE THREAD

**Issue by chuzter** [racoonman2/ReTerraForged#73]
Build failed on any version
![image](https://github.com/racoonman2/ReTerraForged/assets/167421363/99a48724-b0d2-4b5f-a4c3-ff3fc7520073)

**Comment by racoonman2** [comment]
it looks like you might have an incorrect java version, try using java 17 instead

**Comment by chuzter** [comment]
> it looks like you might have an incorrect java version, try using java 17 instead

where are the finished files after compilation?

**Comment by equalizer32** [comment]
`fabric\build\libs` and `forge\build\libs`

**Comment by chuzter** [comment]
> `fabric\build\libs` and `forge\build\libs`

I just want to get and install this mod somehow, but I don't understand what I need to do to get it.jar file as a mod, I don't see it
![image](https://github.com/racoonman2/ReTerraForged/assets/167421363/38ad2d94-7433-43ef-9120-0c6d28d35017)
![image](https://github.com/racoonman2/ReTerraForged/assets/167421363/54b3c583-e355-43ea-bfab-00a880575712)
There is simply no such folder and files here, but gradlew writes about the successful completion of the build
![image](https://github.com/racoonman2/ReTerraForged/assets/167421363/9b1617a7-1bc6-4d98-9166-597c1bc2fb76)
What should I do?

**Comment by equalizer32** [comment]
gradlew build
