### ISSUE TITLE
reterraforged-0.0.4 on server side error [1.19.4]

### ISSUE THREAD

**Issue by estluced** [racoonman2/ReTerraForged#74]
When I try to start my server (there is only one mod and it is reterraforged) I get an error that the mod is trying to load the UI, screenshot below:

![image](https://github.com/racoonman2/ReTerraForged/assets/79997611/08c4a671-76a6-4dc5-a744-a0c87da49b34)

I tried adding a condition that loads the UI only on the client side, but that didn't do anything.

![image](https://github.com/racoonman2/ReTerraForged/assets/79997611/5822ef44-aef9-4b73-858f-df506a2859e7)

Also when I load the client part I get warning:

![image](https://github.com/racoonman2/ReTerraForged/assets/79997611/a640b518-df3a-431e-841b-c55dc1d1ff21)

What could have gone wrong?
Could you please check it out from your end?
Thank you!

**Comment by racoonman2** [comment]
you have to move registerPresetEditors to a separate class

**Comment by racoonman2** [comment]
ill leave this open until in case you still run into any issues

**Comment by estluced** [comment]
> ill leave this open until in case you still run into any issues

Thanks!!!
Yes, I tried moving the initialization of the UI part to a separate class, everything works fine, the server doesn't crash, but I don't understand why reterraforged is not applied when generating the server world.
Can you please tell me how I can customize the level-type in the server.properties file?

**Comment by racoonman2** [comment]
theres a guide for setting it up on servers here https://discord.gg/petc6SF6P2 under the #wiki-faq channel
