### ISSUE TITLE
I can't find the final result

### ISSUE THREAD

**Issue by chuzter** [racoonman2/ReTerraForged#75]
I don't understand where the final files that I need to put in .minecraft/mods are for reterraforged to run on forge 1.20.2. In the folder that I unpacked, I can't figure out which jar file needs to be moved to mods. I was running gradlew.bat and I were told to build successful. Please tell me where to look for files after that, I need the exact location and name of the file. I haven't found any guides on how to do this.
![image](https://github.com/racoonman2/ReTerraForged/assets/167421363/1c91351e-ec45-4d76-b548-01247ddaab8d)

**Comment by racoonman2** [comment]
either fabric/build/libs or forge/build/libs if you built it correctly

**Comment by chuzter** [comment]
> either fabric/build/libs or forge/build/libs if you built it correctly

it was written that build successful
![image](https://github.com/racoonman2/ReTerraForged/assets/167421363/9bcf0e55-a78f-4e18-8312-9d3338b080fc)

but there is no lib folder inside build, neither in forge nor in fabric
![image](https://github.com/racoonman2/ReTerraForged/assets/167421363/0eabbe8c-1fdd-4982-9537-91a1cb487975)
![image](https://github.com/racoonman2/ReTerraForged/assets/167421363/7aa7856d-4fec-4ffd-ac40-8c4ae2f15c92)

**Comment by racoonman2** [comment]
it doesnt look like you actually ran the build command in the screenshot you posted

**Comment by chuzter** [comment]
> it doesnt look like you actually ran the build command in the screenshot you posted

Then what is it?
https://drive.google.com/file/d/1-SKwA7Vo0gVADxGGewEUzk_LBgolPNXx/view?usp=sharing

**Comment by racoonman2** [comment]
gradlew build

**Comment by chuzter** [comment]
> gradlew build

My God, why can't anyone explain this normally? I press gradlew.bat, there is a 'successful build' going on, what should I do next? Can't you explain it clearly? I can't find the final mod that I need, so I'm writing here to figure out where to find it, but I get nothing useful in response.

**Comment by equalizer32** [comment]
![hi-google](https://github.com/racoonman2/ReTerraForged/assets/85794256/cba37b6b-04cb-435f-ae62-01a0ce21cf49)

just search up how to build a mod on google

**Comment by chuzter** [comment]
> ![hi-google](https://private-user-images.githubusercontent.com/85794256/324556757-cba37b6b-04cb-435f-ae62-01a0ce21cf49.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MTMxNzQsIm5iZiI6MTcxMzgxMjg3NCwicGF0aCI6Ii84NTc5NDI1Ni8zMjQ1NTY3NTctY2JhMzdiNmItMDRjYi00MzVmLWFlNjItMDFhMGNlMjFjZjQ5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE5MDc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNWMwYmYyZGIwYTlhMDBiNzYzNTNhNDE4MjhhNTQ4ZTFlZTIwMzUyODg4Mjk5MTYwOTE1OTI4ZGY3ODZkOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AHCXNoxCekAQu3lENZvlfn6Mi4C5NTYB_i79u-Ktatg)
>
> just search up how to build a mod on google

![image](https://github.com/racoonman2/ReTerraForged/assets/167421363/0e683a41-c37b-46a1-a248-e35af1d3f6ef)

Okay, Googling little bit helped me. However, none of the files are working properly. Forge does not run with any jar file. Fabric allows me to start the game, but when I go to the world settings and click done, the game shuts down
![image](https://github.com/racoonman2/ReTerraForged/assets/167421363/5024c185-9824-4ffd-9424-e6c31067eb4a)
I have installed the newest version of fabric, fabric api and forge

**Comment by equalizer32** [comment]
You are also supposed to run gradlew forge:runData and fabric:runData before running gradlew build to generate the language files and if you really want build RTF from the source code then you need to use a [specific commit](https://github.com/racoonman2/ReTerraForged/tree/32d25dc1bdbab7226f377e2d92359bd8cce11438) because since this commit large parts of the code have been disabled for testing purposes and cause the mod to not function. And even then the Forge version won't work because of 2 broken mixins in the MixinChunkStatus class so you would have to disable them for it to work.

**Comment by chuzter** [comment]
> You are also supposed to run gradlew forge:runData and fabric:runData before running gradlew build to generate the language files and if you really want build RTF from the source code then you need to use a [specific commit](https://github.com/racoonman2/ReTerraForged/tree/32d25dc1bdbab7226f377e2d92359bd8cce11438) because since this commit large parts of the code have been disabled for testing purposes and cause the mod to not function. And even then the Forge version won't work because of 2 broken mixins in the MixinChunkStatus class so you would have to disable them for it to work.

how do I disable them?
