### ISSUE TITLE
Stony Mountains

### ISSUE THREAD

**Issue by GabrielSouza108** [racoonman2/ReTerraForged#82]
I'm using 2032 world height and anything above y=150 turns into stone, creating huge stone mountains. I tried many preset variations and they all seem to create the same result. Is there a way to fix this and have them generate with regular grass and trees? since allowing to build mountains to those y levels creates fantastic landscapes, ruined only by this issue.

![2024-05-06_06 04 53](https://github.com/racoonman2/ReTerraForged/assets/169035526/9ddfb793-24a0-46d9-a16f-2a33c0dba800)
![2024-05-06_06 05 17](https://github.com/racoonman2/ReTerraForged/assets/169035526/a30ffdb5-75ee-4096-a157-f887e50ca3c7)
![2024-05-06_06 06 57](https://github.com/racoonman2/ReTerraForged/assets/169035526/681f19e0-642a-4c89-a06d-66045340334a)
![2024-05-06_06 05 37](https://github.com/racoonman2/ReTerraForged/assets/169035526/817e97c4-c52d-4c31-86cf-c32ece7713dd)

**Comment by racoonman2** [comment]
turn up the rock min setting on the surface page

**Comment by racoonman2** [comment]
also this has been removed entirely in the upcoming update
