### ISSUE TITLE
Anyone got a jar?

### ISSUE THREAD

**Issue by PPlayer31** [racoonman2/ReTerraForged#85]
Many people have a v0.06 version of the RTF jar. If possible can anyone send me any? I tried finding anything in discord but no one seems to have uploaded the jar.

**Comment by equalizer32** [comment]
Please don't ask for jars on the GitHub and close this issue. 0.0.7 isn't that far off so you should just wait for that to release.

Edit: you can use this datapack for the time being as it's probably the closest you will get to RTF right now - https://modrinth.com/datapack/lithosphere
