### ISSUE TITLE
I meet a crash

### ISSUE THREAD

**Issue by hkbinbin** [racoonman2/ReTerraForged#87]
It seems that it got problems while solving ResourceKey[minecraft:worldgen/placed_feature / reterraforged:redwood_trees]
[crash-2024-06-21_01.59.11-server.txt](https://github.com/user-attachments/files/15923623/crash-2024-06-21_01.59.11-server.txt)

**Comment by racoonman2** [comment]
this is fixed in the next update but you can temporarily fix it by disabling custom biome features
