### ISSUE TITLE
(Question) Working with other world builders/makers [mod(s)/datapack(s)]

### ISSUE THREAD

**Issue by ghost** [racoonman2/ReTerraForged#88]
For mods like Better Nether, Better End, the BetterX world builder from BClib is used. I wonder if it will be available with world builders like these in the future?

I know the mod is still very much in alpha stages. But showing compatibility with more world builders and mods like this will make your mod more compatible. This will make it more comfortable for mod pack makers or people who collect mod packs to choose your mod. I think the number of downloads of your mod could increase. 

The example I am talking about is the world builder:
![Ekran görüntüsü 2024-06-22 140058](https://github.com/racoonman2/ReTerraForged/assets/46456267/449b8daa-ce83-44fa-810e-da042330a2f0)

**Comment by racoonman2** [comment]
you should still be able to get them to work together by applying your rtf preset before selecting the bclib world type
