### ISSUE TITLE
(Server crashed) Exception in server tick loop

### ISSUE THREAD

**Issue by Schmarbier** [racoonman2/ReTerraForged#92]
Sorry for the English, I used a translator.

Hi, I'm creating a server for Minecraft 1.20.1 and when I only use the Terraforged mod (1.20.1), I get the warning: "Failed to parse level-type terraforged, defaulting to minecraft".

In my server.properties as I saw in the previous version (TerraForged) to be able to add it to a server you have to change the level-seed. (level-type=terraforged)

I have attached the log files.

[crash-2024-07-02_00.34.05-server.txt](https://github.com/user-attachments/files/16061446/crash-2024-07-02_00.34.05-server.txt)
[latest.txt](https://github.com/user-attachments/files/16061447/latest.txt)

In my server.properties, as I saw in the previous version (TerraForged), to add it to a server, you have to change the level-seed to **level-type=terraforged**.

After that, searching the internet, I found that you can generate a map from datapacks. I did that, but the server crashed. I have attached the files.

[crash-2024-07-02_00.15.58-server.txt](https://github.com/user-attachments/files/16061454/crash-2024-07-02_00.15.58-server.txt)

Any solution? ty :)

**Comment by racoonman2** [comment]
0.0.5 is outdated, update to 0.0.6 or wait for the next update
