### ISSUE TITLE
Question: Does 0.0.7 mean Mod will be Stable / Without much bugs? When will it be?

### ISSUE THREAD

**Issue by seeditch** [racoonman2/ReTerraForged#93]
I never use github before, but want to ask a question (discord is locked). Sorry if they ask question a lot like this. I'm very confuse by naming scheme, and am want in using this mod in server or modpack whenever its ready. But I am not understand when it is ready because I do not understand what version name mean the mod is stable and usable. If you know please tell me. Thank you very much!

**Comment by Feuerswut** [comment]
oh hell no...
it will be runnable, but there will be some bugs likely

a single developer can only fix so many bugs without a semi-public test.

that'll take some more time as well as the to-do list of features that will come even later (3d rivers)

**Comment by AnAnonymousPotato** [comment]
Does anyone know what is the expected, approximate date for when the 0.0.7 version will release? I know it's very hard for a single developer to make it in a less amount of time and I'm not forcing them to overwork make it as soon as possible; but I just want to know when will it be released (1 week, 1 month, or half a year?) Thanks.

**Comment by equalizer32** [comment]
There is no ETA for 0.0.7
