### ISSUE TITLE
Crash when use in Server

### ISSUE THREAD

**Issue by VVittgenstein** [racoonman2/ReTerraForged#95]
Minecraft Version : {1.20.1}
[latest.log](https://github.com/user-attachments/files/16416219/latest.log)

Core : Forge

Operating System : {Windows}

[latest.log](https://github.com/user-attachments/files/16416220/latest.log)
[Modlist (2).txt](https://github.com/user-attachments/files/16416230/Modlist.2.txt)

**Comment by racoonman2** [comment]
this has already been fixed in the upcoming version, but you can prevent it for now by disabling custom biome features on the last page of the settings
