### ISSUE TITLE
Feature Request - Version inheritance of both RTF mod and Minecart.

### ISSUE THREAD

**Issue by AC5174765920** [racoonman2/ReTerraForged#96]
The issue is, whenever I removed RTF from mod folder and re-copy it to the folder, the worldgen forgets its seed and will abruptly have new chunks at the border, which makes cliff-like new border. And the same happens when you upgrade your world to another version of Minecraft.

Thus confines the players to only play one version of Minecraft and one version of RTF. It will be very nice if the players' world can have one preset one seed to inherit. When you either change RTF versions or Minecraft versions it will still work.

**Comment by racoonman2** [comment]
rtf is already compatible across minecraft versions, however making it compatible across rtf versions isnt possible and not something i intend on adding

**Comment by AC5174765920** [comment]
> rtf is already compatible across minecraft versions, however making it compatible across rtf versions isnt possible and not something i intend on adding

Hello thank you for your response. I understand it might be frustrating to add RTF versions compatibility across those in-dev versions. But if the RTF 0.0.7 or higher version comes out, will there be mod version compatibility? Because in the long term it will definitely be better for people to inherit the world. Instead of dump the older Minecraft save when you want to try a newer version of RTF
