### ISSUE TITLE
Bug - Resource pack info not load (1.20.2)

### ISSUE THREAD

**Issue by Hira-Dimenios** [racoonman2/ReTerraForged#97]
Hello!
I've been looking for a solution to this problem for several days, but finding nothing I finally decided to report it.

The images speak for themselves, but basically the game fails to load the "resource pack info". The result is that the menu buttons do not appear correctly and make the mod very difficult to use.

Mod downloaded from 9minecraft.net ( https://www.9minecraft.net/reterraforged-mod/ )

![RTF 01](https://github.com/user-attachments/assets/3b91944b-5032-40eb-8ba6-44c9f34011f5)
![RTF 02](https://github.com/user-attachments/assets/85b5aa9a-74fa-4001-9012-7353efb707b3)
![RTF 03](https://github.com/user-attachments/assets/e801bb14-7c2b-4aec-b1a3-8a47af255fca)

**Comment by racoonman2** [comment]
9minecraft isn't a legitimate place to get mods, and theres a good chance they included some sort of malware in whatever you downloaded

**Comment by racoonman2** [comment]
There isn't any official downloads for RTF atm so if you want a safe version you'll have to wait until 0.0.7 releases

**Comment by racoonman2** [comment]
and for future reference only download mods from these sites, anything else is most likely not safe 
https://www.curseforge.com/
https://www.modrinth.com/

**Comment by Hira-Dimenios** [comment]
Thank you very much for your quick answers.
Your mod seems to be quite widespread among players already but the only site where I found a .jar version of it was on 9minecraft. Usually I go to Curse.
I will try with the github version.
Thanks for the work you do!
