### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by I2pRandom** [racoonman2/ReTerraForged#99]
I'm wondering if this is still being maintained or a stale repository? It's been a while since there was a commit. 
Was development moved to a different Repo?

**Comment by equalizer32** [comment]
The development was moved to a private repository.

**Comment by Macintosh-Fan** [comment]
So, not open-source anymore?

**Comment by equalizer32** [comment]
> So, not open-source anymore?

The mod is currently being developed in private. This repo will be updated once 0.0.7 releases.
